### ISSUE TITLE
Dynamic resizing does not work

### ISSUE THREAD

**Issue by Jumpst3r** [Jumpst3r/proj-kvs-g1-2018#2]
# Dynamic resizing concept:
When the hash table load factor `KVS->load / KVS->maxsize` exceeds 0.75, we create a new KVS + hashtable of size `1.5 * KVS->maxsize`. We then need to loop through all elements of the old KVS and insert them with `void insert_new(kvs_t *kvsn, kvp_t kvp)` into the new KVS, then we overwrite the KVS pointer.

see the `resize()` for more information

## The problem is
The `void insert_new(kvs_t *kvsn, kvp_t kvp)` is stuck in the while loop.

**Comment by TheLoooser** [comment]
Initial problem solved. Resizing the hash table works fine. Although a new problem occurred: After a resize, it is possible to insert an existing key

**Comment by Jumpst3r** [comment]
Good job! Can you create a new issue? It's a good way to keep track of things to do!
